### ISSUE TITLE
⚠️ ERROR - ENOENT: no such file or directory

### ISSUE THREAD

**Issue by johnrlive** [ndro/vue-webpack-buefy#1]
Please see screenshot.

![1__jr_jrs-macbook-air-3_____vue-templates__zsh_](https://user-images.githubusercontent.com/535279/33157679-d179e40e-cfd1-11e7-9ebc-3a5e86ca9781.png)

**Comment by ndro** [comment]
@johnrlive I'm sorry. I think I did a mistake. I will change the README file and Getting Started content.

Thank you for your review.
